export const columnsStruktura = [
    {
      field: "wyt",
      headerName: "Nr wytopu",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 100,
    },
    {
      field: "gat",
      headerName: "Gatunek",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 130,
      editable: false,
    },
    {
      field: "rodzMet",
      headerName: "Rodzaj metalu",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 150,
      editable: false,
    },
    {
      field: "sfer",
      headerName: "Stopień sferoidalności grafitu [%]",
      width: 230,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "wydz",
      width: 225,
      headerClassName: "tableHeader",
      headerName: 'Liczba wydzieleń grafitu [1/mm2]',
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "graf",
      headerName: "Udział grafitu [%]",
      width: 130,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "perl",
      headerName: "Udział perlitu [%]",
      width: 130,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "fer",
      headerName: "Udział ferrytu [%]",
      width: 130,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "data",
      headerName: "Data modyfikacji",
      headerAlign: "center",
      align: "center",
      headerClassName: "tableHeader",
      width: 150,
    },
  ];