export const columnsMech = [
    {
        field: "wyt",
        headerName: "Nr wytopu",
        headerClassName: "tableHeader",
        headerAlign: "center",
        align: "center",
        width: 100,
    },
    {
        field: "gat",
        headerName: "Gatunek",
        headerClassName: "tableHeader",
        headerAlign: "center",
        align: "center",
        width: 130,
        editable: false,
    },
    {
        field: "rodzMet",
        headerName: "Rodzaj metalu",
        headerClassName: "tableHeader",
        headerAlign: "center",
        align: "center",
        width: 150,
        editable: false,
    },
    {
        field: "wytrzRm",
        width: 270,
        headerClassName: "tableHeader",
        headerName: 'Wytrzymałość na rozciąganie Rm [MPa]',
        headerAlign: "center",
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "granicaRp",
        width: 245,
        headerClassName: "tableHeader",
        headerName: 'Granica plastyczności Rp0,2 [MPa]',
        headerAlign: "center",
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "wydl",
        width: 245,
        headerClassName: "tableHeader",
        headerName: 'Wydłużenie względne A10 [%]',
        headerAlign: "center",
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "young",
        width: 200,
        headerClassName: "tableHeader",
        headerAlign: "center",
        headerName: 'Moduł Younga E [GPa]',
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "twar",
        width: 150,
        headerClassName: "tableHeader",
        headerAlign: "center",
        headerName: 'Twardość',
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "udar",
        width: 150,
        headerClassName: "tableHeader",
        headerAlign: "center",
        headerName: 'Udarność',
        align: "center",
        type: "number",
        editable: false,
    },
    {
        field: "data",
        headerName: "Data modyfikacji",
        headerAlign: "center",
        align: "center",
        headerClassName: "tableHeader",
        width: 150,
    },
];