import DeleteOutlinedIcon from '@mui/icons-material/DeleteOutlined';
import { IconButton} from '@mui/material';

export const columns = [
    {
      field: "wyt",
      headerName: "Nr wytopu",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 120,
    },
    {
      field: "gat",
      headerName: "Gatunek",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 150,
      editable: false,
    },
    {
      field: "rodzMet",
      headerName: "Rodzaj metalu",
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      width: 150,
      editable: false,
    },
    {
      field: "C",
      headerName: "C",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Si",
      headerName: "Si",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Mn",
      headerName: "Mn",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Mg",
      headerName: "Mg",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "P",
      headerName: "P",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "S",
      headerName: "S",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Cu",
      headerName: "Cu",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Ce",
      headerName: "Ce",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "La",
      headerName: "La",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Zr",
      headerName: "Zr",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Bi",
      headerName: "Bi",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "Ca",
      headerName: "Ca",
      width: 70,
      headerClassName: "tableHeader",
      headerAlign: "center",
      align: "center",
      type: "number",
      editable: false,
    },
    {
      field: "data",
      headerName: "Data modyfikacji",
      headerAlign: "center",
      align: "center",
      headerClassName: "tableHeader",
      width: 210,
    },
  ];